# Generated by Django 4.1.7 on 2023-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_projectinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
