# Generated by Django 4.1.7 on 2023-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_projectinfo_image_alter_projectinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
