# Generated by Django 4.1.7 on 2023-04-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_projectinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
